'''
This script converts a picture generated by the NVidia AI tool (https://build.nvidia.com/stabilityai/stable-diffusion-xl)
and saved in a JSON file in BASE64 encoding.

2025.01.02
'''

import json
import base64

# Replace with a proper file name
FILE_NAME= "AI Gen- Sea.json"

def main():
    print()
    print("NVidia AI Picture Encoder")
    print("Reading the input JSON file... ".ljust(40, " "), end= "")

    data= {}
    with open(FILE_NAME, "r") as in_jason:
        data= json.load(in_jason)

    if "artifacts" not in data.keys():
        print("There is no \"artifacts\" key in the input data")
        exit()

    # Extracting artifacts
    artifacts= data.get("artifacts")
    pic_data= artifacts[0]

    if "base64" not in pic_data:
        print("There is no \"base64\" section in the input data")
        exit()

    print("Done")

    # Extracting picture encoded in base64
    print("Decoding and saving a picture...")

    encoded_pic= pic_data.get("base64")
    decoded_pic= base64.b64decode(encoded_pic)

    # Creting a file name for the picture
    pic_name= FILE_NAME.split(".")[0]+ ".jpg"

    # Writing the output data as a JPEG picture
    with open(pic_name, "+bw") as out_pic:
        out_pic.write(decoded_pic)

    print("Done")
    print()

if __name__== "__main__":
    main()
